// Generated by purs bundle 0.14.2
var PS = {};
(function(exports) {
  "use strict";

  exports.unit = {};
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function($PS) {
  // Generated by purs version 0.14.2
  "use strict";
  $PS["Data.Unit"] = $PS["Data.Unit"] || {};
  var exports = $PS["Data.Unit"];
  var $foreign = $PS["Data.Unit"];
  exports["unit"] = $foreign.unit;
})(PS);
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.14.2
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  "use strict";
  var readlineSync =require("readline-sync");

  exports.readLine = function (x) {
    return function () {
      return readlineSync.question(x)
    }
  }
})(PS["Readline"] = PS["Readline"] || {});
(function($PS) {
  "use strict";
  $PS["Readline"] = $PS["Readline"] || {};
  var exports = $PS["Readline"];
  var $foreign = $PS["Readline"];
  exports["readLine"] = $foreign.readLine;
})(PS);
(function($PS) {
  "use strict";
  $PS["Mal.Step0"] = $PS["Mal.Step0"] || {};
  var exports = $PS["Mal.Step0"];
  var Data_Unit = $PS["Data.Unit"];
  var Effect_Console = $PS["Effect.Console"];
  var Readline = $PS["Readline"];                
  var read = function (s) {
      return s;
  };
  var print = function (s) {
      return s;
  };
  var loop = function __do() {
      var line = Readline.readLine("user> ")();
      if (line === ":q") {
          return Data_Unit.unit;
      };
      if (line === ":Q") {
          return Data_Unit.unit;
      };
      Effect_Console.log(line)();
      return loop();
  };
  var main = loop;
  var $$eval = function (s) {
      return s;
  };
  var rep = function ($1) {
      return print($$eval(read($1)));
  };
  exports["main"] = main;
  exports["loop"] = loop;
  exports["read"] = read;
  exports["eval"] = $$eval;
  exports["print"] = print;
  exports["rep"] = rep;
})(PS);
PS["Mal.Step0"].main();